

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npm run env:test
  displayName: 'Executing Playwright Scripts'
  env:
    CI: 'true'
- task: PublishTestResults@2
  inputs: 
    testResultsFormat: 'JUnit'
    testResultsFiles: 'results.xml'
    testRunTitle: 'Grip Automation Results'
  condition: succeededOrFailed()
schedules:
- cron: "30 12 * * *"
  displayName: Daily 12.30pm US timezone
  branches:
    include:
    - main
  always: true